[tasks.packaging-deb]
script = '''
mkdir -p packaging/deb/usr/bin packaging/deb/etc/systemd/system
cp target/release/lb2d packaging/deb/usr/bin/lb2d
cp systemd-unit/lb2d.service packaging/deb/etc/systemd/system/lb2d.service
fakeroot dpkg-deb --build packaging/deb
'''
dependencies = ["build-release"]

[tasks.install-by-pkgbuild]
script = '''
cd packaging/pacman
echo "===== makepkg ====="
makepkg -sf
echo "===== Install lb2d package ====="
sudo pacman -U lb2d-*-*-x86_64.pkg.tar.xz
'''

[tasks.act]
script = '''
act --artifact-server-path ./output
'''

[tasks.clean]
clear = true
script = '''
rm -rf target
rm -rf output/*
rm -rf packaging/pacman/{pkg,src}
rm -rf packaging/pacman/lb2d-*
'''
