name: Build and Package

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Install require packages
              run: |
                sudo apt-get update
                sudo apt-get install dpkg fakeroot
                cargo install cargo-make

            - run: makers test
            - run: makers packaging-deb

            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                name: lb2d.deb
                path: packaging/deb.deb
